// main.js
const comedogenicIngredients = [
    "1-acetoxyhexadecane",
    "1-hexadecanol acetate",
    "1-hexadecanol",
    "Acetic acid hexadecyl ester",
    "Acetylated Lanolin",
    "Acetylated Lanolin Alcohol",
    "Acetylated wool fat",
    "Acetylated wool wax",
    "Adansonia digitata l.",
    "Agar",
    "Ahnfeltiopsis concinna extract",
    "Alaria esculenta extract",
    "Alga bladderwrack",
    "Algae",
    "Algae Extract",
    "Algin",
    "Alginate",
    "Alginic acid",
    "Algea",
    "Aphanothece sacrum polysaccharide",
    "Arthrospira plantensis",
    "Ascophyllum nodosum extract",
    "Asparagopsis armata extract",
    "Baobab",
    "Beeswax",
    "Bismuth",
    "Bryopsis africana",
    "Butyl Octadecanoate",
    "Butyl Stearate",
    "Butyl Stearic acid",
    "Butyrospermum",
    "Cacao seed butter",
    "Capea biruncinata var. denuda sonder",
    "Capea biruncinata var. elongata sonder",
    "Carageenan gum",
    "Carastay c",
    "Caulerpa lentillifera extract",
    "Caulerpa filiformis",
    "Carrageenan",
    "Carrageenan Moss",
    "Cera alba",
    "Cera bianca",
    "Cera flava",
    "Cera olea",
    "Cetearyl Alcohol + Ceteareth 20",
    "Cetyl Acetate",
    "Chaetomorpha linum (aerea) cladophora radiosa",
    "Chlamydomonas reinhardtii extract",
    "Chlorella",
    "Chlorophyceae",
    "Chondrus Crispus (aka Irish Moss or Carageenan Moss)",
    "Cladophora cf. subsimplex",
    "Cladosiphon okamuranus extract",
    "Coal Tar",
    "Coco-caprate",
    "Coco-caprylate",
    "Cocoa Butter",
    "Coconut Alkanes",
    "Coconut Butter",
    "Coconut Extract",
    "Coconut Nucifera extract",
    "Coconut Oil",
    "Cocos nucifera oil",
    "cocos nucifera seed butter",
    "Coenochloris signiensis extract",
    "Colloidal Sulfur",
    "Cotton Awws Oil",
    "Cotton Seed Oil",
    "Corallina officinalis extract",
    "Corn",
    "Corn oil",
    "Creosote",
    "Cystoseira tamariscifolia extract",
    "D & C Red # 17",
    "D & C Red # 21",
    "D & C Red # 3",
    "D & C Red # 30",
    "D & C Red # 36",
    "Decyl Oleate",
    "Decyloleate",
    "Dicotyledons succinate",
    "Dictyopteris membranacea",
    "Dictyopteris polypodioides",
    "Diethylhexyl sodium sulfosuccinate",
    "Diisooctyl succinate",
    "Dilsea carnosa extract",
    "Dioctyl sodium sulfosuccinate",
    "Dioctyl Succinate",
    "Disodium laureth sulfosuccinate",
    "Disodium Monooleamido",
    "Disodium Monooleamido peg 2 sulfosuccinate",
    "Disodium oleamido peg-2 sulfosuccinate",
    "Dodecanoic acid",
    "Dodecoic acid",
    "Dodecylic acid",
    "Dunaliella salina extract",
    "Duodecylic acid",
    "Durvillaea antarctica extract",
    "Ecklonia cava",
    "Ecklonia cava extract",
    "Ecklonia radiata",
    "Enteromorpha compressa extract",
    "Ethoxylated Lanolin",
    "Ethylhexyl Palmitate",
    "Ethylhexyl Stearate",
    "Eucheuma spinosum extract",
    "Fucoxanthin",
    "Fucus serratus",
    "Fucus vesiculosus",
    "Gamtae extract",
    "Gelidiella acerosa extract",
    "Gelidium amansii extract",
    "Gigartina stellata extract",
    "Glyceryl monostearate",
    "Glyceryl Stearate SE",
    "Glyceryl-3 Diisostearate",
    "Glycine soja oil",
    "Glycine max",
    "Gracilariopsis chorda extract",
    "Haematococcus pluvialis extract",
    "Haematococcus pluvialis",
    "Haslea ostrearia extract",
    "Hexadecanol acetate",
    "Hexadecyl Acetate",
    "Hexadecyl Alcohol",
    "Himanthalia elongata extract",
    "Hizikia fusiforme extract",
    "Hydrogenated Vegetable Oil",
    "Hydrolyzed rhodophycea extract",
    "Hydrous magnesium silicate",
    "Hypnea musciformis extract",
    "Hypneaceae extract",
    "Irish Moss",
    "Isocetyl Alcohol",
    "Isocetyl Stearate",
    "Isodecyl Oleate",
    "Isohexadecanol",
    "Isohexadecyl alcohol",
    "Isohexadecyl stearate",
    "Isooctadecyl isooctadecanoate",
    "Isopalmitic alcohol",
    "Isopalmityl alcohol",
    "Isopropyl isodecanoate",
    "Isopropyl Isostearate",
    "Isopropyl Linolate",
    "Isopropyl Myristate",
    "Isopropyl Palmitate",
    "Isostearyl Isostearate",
    "Isostearyl Neopentanoate",
    "Jania rubens extract",
    "Jojoba wax",
    "Kappaphycus alvarezii extract",
    "Karite",
    "Kelp",
    "Kousou ekisu",
    "Laminaria",
    "Laminaria Digitata Extract",
    "Laminaria Saccharina Extract (Laminaria Saccharine)",
    "Lanolin acetate",
    "Lanolin alcohol acetate",
    "Lanolin polyoxyethylene ether",
    "Laureth-23",
    "Laureth-4",
    "Lauric Acid",
    "Laurostearic acid",
    "Lcd",
    "Linolate",
    "Liquor carbonis detergens",
    "Liquor picis carbonis",
    "Lithothamnium calcareum powder",
    "Lpc",
    "Macroalgae",
    "Macrocystis pyrifera extract",
    "Mangifera indica seed butter",
    "Mango Butter",
    "Marula",
    "Marula oil",
    "Methylsilanol mannuronate",
    "Mink Oil",
    "Moss",
    "Myristate",
    "Myristic Acid",
    "Myristyl",
    "Myristyl Lactate",
    "Myristyl Myristate",
    "Myristyl Propionate",
    "N-hexadecyl alcohol",
    "N-hexadecyl ethanoate",
    "Octadecanoic acid",
    "Octadecyl heptanoate",
    "Octyl Palmitate",
    "Octyl Stearate",
    "Oleth-3",
    "Oleth-3 phosphate",
    "Oleyl Alcohol",
    "Palmaria palmata extract",
    "Palmityl Acetate",
    "Palmityl Alcohol",
    "Parkii",
    "PEG 2 Sulfosuccinate",
    "PEG 2- Sulfosuccinate",
    "PEG 16 Lanolin",
    "PEG 200 Dilaurate",
    "PEG-75",
    "PEG 8 Stearate",
    "Pelvetia canaliculata extract",
    "PES",
    "Phaeodactylum tricornutum extract",
    "Phaeophyceae",
    "Pix carbonis",
    "PG Monostearate",
    "PGMS",
    "PPG-2 Myristyl",
    "PPG 2 Myristyl Propionate",
    "PPG 2 Myristyl Ether Propionate",
    "Plankton",
    "Polyethylene glycol 200",
    "Polyethylene glycol dodecyl ether"] 

// Export the ingredients list for use in other files
export default comedogenicIngredients;
